---
title: 'Data viz: ggplot 1'
output: github_document
---
Load all necessary pacakges.
```{r load packages, message = FALSE}
library(tidyverse)
library(ggridges)
```

Get the data for plotting today.
```{r pull in data}
# Pull 3 weather stations from NOAA dataset
df_weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
# Rename and clean variables
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Let's make a plot!

```{r first plot}
ggplot(df_weather, aes(x = tmin, y = tmax)) +
  geom_point()
```

Pipes and stuff
```{r pipes and saving plot}
ggp_nyc_weather <- 
  df_weather |> 
    filter(name == "CentralPark_NY") |> 
    ggplot(aes(x = tmin, y = tmax)) +
    geom_point()

ggp_nyc_weather
```

## Fancy plot
```{r color and smooth}
ggplot(df_weather, aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = 0.3) +
  geom_smooth(se = FALSE)
```

Plot with facets
```{r facets}
ggplot(df_weather, aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

Let's try a different plot. temps are boring
```{r tmax vs date}
ggplot(df_weather, aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.3) +
  geom_smooth(se = 0) + 
  facet_grid(. ~ name)
```

Try assigning specfic colors
```{r color assignment}
df_weather |> 
  filter(name != "CentralPark_NY") |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(alpha = 0.7, size = 0.5)
```

